### ISSUE TITLE
ACM Pricing

### ISSUE THREAD

**Issue by mjurczyk** [cloudkj/scar#10]
$0.50 sounds nice, but doesn't ACM charge additional $400.00 for setup (after 30 days trial)?

https://aws.amazon.com/certificate-manager/pricing/

May be good to point out in the description?

**Comment by cloudkj** [comment]
Hi @mjurczyk - the pricing you're referring to is for private certificates. Public certificates (which is what SCAR uses) are free:

> Public SSL/TLS certificates provisioned through AWS Certificate Manager are free. You pay only for the AWS resources you create to run your application.

Hope that helps.

**Comment by mjurczyk** [comment]
Right, thanks for the clarification!
